"""add snapshot to games

Revision ID: 37cc5785766a
Revises: ef26b80eb21b
Create Date: 2026-04-30 20:47:45.616447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cc5785766a'
down_revision: Union[str, Sequence[str], None] = 'ef26b80eb21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('snapshot_json', sa.Text(), nullable=True))
    op.add_column('games', sa.Column('snapshot_turn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'snapshot_turn')
    op.drop_column('games', 'snapshot_json')
    # ### end Alembic commands ###
